#!/usr/bin/env escript
%%! -smp enable -sname erlshell -setcookie antidote
main(_Args) ->
  rpc:call(antidote@node1, inter_dc_manager, start_bg_processes, [stable]),
  rpc:call(antidote@node2, inter_dc_manager, start_bg_processes, [stable]),
  {ok, Desc1} = rpc:call(antidote@node1, inter_dc_manager, get_descriptor, []),
  {ok, Desc2} = rpc:call(antidote@node2, inter_dc_manager, get_descriptor, []),
  rpc:call(antidote@node1, inter_dc_manager, observe_dcs_sync, [Desc2]),
  rpc:call(antidote@node2, inter_dc_manager, observe_dcs_sync, [Desc1]),
  io:format("Connection setup!").
